
services:
  mensabot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: MensaTelegramBot
    restart: always
    environment:
      - TZ=Europe/Berlin  # Set timezone if needed
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
